name: ✨ Feature Request
description: Request a new feature or enhancement for the school activities website
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help our Copilot coding agent understand and implement your request.

  - type: input
    id: feature-title
    attributes:
      label: Feature Title
      description: A clear and concise title for your feature request
      placeholder: "Example: Add ability to export activity participant lists to Excel"
    validations:
      required: true

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: What type of feature are you requesting?
      options:
        - Student features (browsing, signup, profile)
        - Teacher features (management, administration)
        - Activity management (create, edit, delete activities)
        - Reporting and analytics
        - Communication features (notifications, emails)
        - Search and filtering improvements
        - Mobile/accessibility improvements
        - Data export/import features
        - Integration with other systems
        - Other
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Why do you need it?
      placeholder: "Example: Currently, teachers have to manually copy student names from the website to create attendance sheets, which is time-consuming and error-prone."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see implemented
      placeholder: "Example: Add an 'Export to Excel' button on each activity page that downloads a spreadsheet with all registered students' names and email addresses."
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: List specific requirements that define when this feature is complete
      placeholder: |
        Example:
        - An "Export" button appears on each activity detail page
        - Clicking the button downloads an Excel file (.xlsx format)
        - The file contains columns: Student Name, Email, Registration Date
        - Only teachers can access the export feature (requires login)
        - The filename includes the activity name and current date
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: Who would use this feature?
      description: Select the primary users who would benefit from this feature
      options:
        - Teachers/Staff only
        - Students only
        - Both teachers and students
        - School administrators
        - Parents/Guardians
        - Everyone
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature for school operations?
      options:
        - High - Essential for daily operations
        - Medium - Would improve efficiency significantly
        - Low - Nice to have, but not critical
    validations:
      required: true

  - type: textarea
    id: additional-details
    attributes:
      label: Additional Details
      description: Any other context, mockups, examples, or technical considerations
      placeholder: "Include any specific requirements, design ideas, or examples from other systems you've seen"

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches to solve this problem?
      placeholder: "Example: We could manually create Excel files, but it's time-consuming. Google Sheets integration might work too."

  - type: checkboxes
    id: verification
    attributes:
      label: Verification
      description: Please confirm the following
      options:
        - label: I have checked that this feature hasn't already been requested
          required: true
        - label: This feature would benefit multiple users (not just myself)
          required: true